### ISSUE TITLE
Where is travel_api.cpp? 

### ISSUE THREAD

**Issue by mengmeng4263** [darrenjkt/TRAVEL#1]
I can not find travel_api.cpp in this repo or the original repo either.

**Comment by darrenjkt** [comment]
I have a [cpp demo code](https://github.com/darrenjkt/TRAVEL/blob/dc48204c08a37d74748091f870f41dc44eefbbe4/travel_demo.cpp) if that's what you're looking for? 

If you're looking for class definitions for the TRAVEL, they actually do everything in the tgs.hpp header file so you can just include that (see this [line](https://github.com/darrenjkt/TRAVEL/blob/dc48204c08a37d74748091f870f41dc44eefbbe4/travel_demo.cpp#L22))

**Comment by mengmeng4263** [comment]
Thanks for the quick response! I saw the part 

To include in any project, structure the files like this:

my_project
- travel
  - travel_api.py 
  - src
    - tgs.hpp
    - travel_api.cpp

You mentioned travel_api.cpp and do you mean that travel_demo.cpp is the same as travel_api.cpp?

**Comment by darrenjkt** [comment]
Sorry about that! I renamed the file but didn't change the readme. The "travel_api.cpp" is "travel_pybind.cpp". I've fixed that up in the readme.

**Comment by mengmeng4263** [comment]
Thanks for the update!
