### ISSUE TITLE
Incompatible function arguments

### ISSUE THREAD

**Issue by tzsombor95** [darrenjkt/TRAVEL#2]
Hy,
I got the following error at running travel_demo.py:
File "TRAVEL/travel_demo.py", line 12, in <module>
    ground_pc, nonground_pc, ground_inds = ground_seg.estimate_ground(in_pc)
  File "/TRAVEL/travel_api.py", line 34, in estimate_ground
    self.tgs.estimateGround(in_pc, ground_pc, nonground_pc, ground_inds)
TypeError: estimateGround(): incompatible function arguments. The following argument types are supported:
    1. (self: travel.TravelGroundSeg, arg0: std::vector<Eigen::Matrix<double, 3, 1, 0, 3, 1>, std::allocator<Eigen::Matrix<double, 3, 1, 0, 3, 1> > >, arg1: std::vector<Eigen::Matrix<double, 3, 1, 0, 3, 1>, std::allocator<Eigen::Matrix<double, 3, 1, 0, 3, 1> > >, arg2: std::vector<Eigen::Matrix<double, 3, 1, 0, 3, 1>, std::allocator<Eigen::Matrix<double, 3, 1, 0, 3, 1> > >, arg3: std::vector<Eigen::Matrix<double, 3, 1, 0, 3, 1>, std::allocator<Eigen::Matrix<double, 3, 1, 0, 3, 1> > >) -> None

Invoked with: <travel.TravelGroundSeg object at 0x7f80503d8fb0>, std::vector<Eigen::Vector3d> with 0 elements.
Use numpy.asarray() to access data., std::vector<Eigen::Vector3d> with 0 elements.
Use numpy.asarray() to access data., std::vector<Eigen::Vector3d> with 0 elements.
Use numpy.asarray() to access data., std::vector<Eigen::Vector3d> with 0 elements.
Use numpy.asarray() to access data.

Did you forget to `#include <pybind11/stl.h>`? Or <pybind11/complex.h>,
<pybind11/functional.h>, <pybind11/chrono.h>, etc. Some automatic
conversions are optional and require extra headers to be included
when compiling your pybind11 module.

**Comment by darrenjkt** [comment]
Looks like you're calling the estimateGround function with an empty pointcloud

**Comment by tzsombor95** [comment]
OK, I changed the path of the pointcloud file, but I got the same error. 
#3 is the same problem, let's continue there, and I close this issue.
