### ISSUE TITLE
Cant process any .pcd

### ISSUE THREAD

**Issue by fatrybl** [darrenjkt/TRAVEL#3]
Hello!
Great thank for you python wrapper for TRAVEL lib. 
I tried to launch it with different .pcd files but always get this 
![image](https://user-images.githubusercontent.com/22779281/209667993-4a44d1a1-a75e-465d-aab7-c4e8551303a7.png)

Could you please help with this issue ?
if any extra info is needed, im ready to provide with it

**Comment by darrenjkt** [comment]
Does the travel_demo.py work with the provided demo.pcd?

**Comment by fatrybl** [comment]
> Does the travel_demo.py work with the provided demo.pcd?

Unfortunately, no. It says that point cloud has shape of (53303, 3) and than the same error occurs. I also tested Patchwork++ on same clouds and it worked fine.

**Comment by darrenjkt** [comment]
does the code work when you try it with the cpp demo code? travel_demo.cpp

**Comment by fatrybl** [comment]
Sorry, can`t build cpp code, error occurs (maybe because i`m not that experienced in c++ buildings. but i`m ready to test anything that is needed): 
![image](https://user-images.githubusercontent.com/22779281/210066634-7feadd78-dac1-47e9-8fd5-213d0c07a0d5.png)

**Comment by tzsombor95** [comment]
Hy,
I got the same error, when running travel_demo.py. I tested the cpp version of demo code, it works fine with the demo.pcd file.
I also tried in your docker, and the python script worked fine. Maybe there is eigen or pcl library incompatibility.
I use pcl-1.10 version, because I had issues in installing pcl-1.8. 
Could this be a problem?

**Comment by fatrybl** [comment]
@tzsombor95  as i see, you have managed to compile c++ version, did you face the same problem as me with compilation ( as in the last attached screenshot) ?

**Comment by tzsombor95** [comment]
@fatrybl No. The compiler ran without any problems.

**Comment by darrenjkt** [comment]
hmm I'm not too sure how to troubleshoot the build with that kind of error as a lot of build errors is often linked to your environment. Try to stick with the specified library versions in this repo.

I have provided a docker image which should work out-of-the-box. Maybe give that a shot? I've provided a docker/run.sh script which should automatically pull the image `darrenjkt/travel:v1.0`. Make sure to edit the mount paths. Also, you don't need a GPU so you can remove the nvidia-related lines of code.

**Comment by fatrybl** [comment]
@darrenjkt i managed to run TRAVEL in docker successfully, but out of the docker still not. 
Probably the problem is in Pybind, idk. The input point cloud is type of numpy array (N,M) shape with np.float64 dtype. Then its transformed to open3d.cuda.pybind.utility.Vector3dVector, and then goes as input to self.tgs.estimateGround() func, which throughs TypeError  of an input cloud argument . The input point cloud is definitely correct and not empty. In docker the script works perfectly on the input .pcd
I use Python 3.10 
![image](https://user-images.githubusercontent.com/22779281/213152175-00a2907f-d0c9-41f2-afda-eb1be4f640e4.png)

**Comment by fatrybl** [comment]
Update:
i launched out of docker with Python 3.7 conda env, it worked fine. so the problem is is Pybinding 11 and Python 3.10. Even though i updated pybind to version 2.10.1, it did not fix the problem. So maybe it makes sense to add this python version limitation to readme
